# Generated by Django 5.2.11 on 2026-03-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='external_transaction_id',
            field=models.CharField(blank=True, help_text="Transaction ID from company's payment system", max_length=255, null=True),
        ),
    ]
