# Generated by Django 5.2.11 on 2026-03-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_company_order_external_transaction_id'),
        ('users', '0002_shippingaddress_user_company_user_external_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('INVENTORY_LOCKED', 'Inventory Locked'), ('BALANCE_CHECK_PENDING', 'Balance Check Pending'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=25),
        ),
    ]
