# Generated by Django 5.2.11 on 2026-03-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_address_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tx_hash',
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
