# Generated by Django 5.2.11 on 2026-03-03 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(blank=True, help_text='Hashed password for portal login', max_length=255)),
                ('client_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('secret_key', models.CharField(editable=False, max_length=128)),
                ('webhook_url', models.URLField(blank=True, help_text='URL to receive payment webhooks')),
                ('webhook_secret', models.CharField(blank=True, editable=False, help_text='Secret for signing webhook payloads', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CHAT_REQUEST', 'Chat Request'), ('CHAT_HISTORY', 'Chat History Request'), ('ORDER_CREATED', 'Order Created'), ('WEBHOOK_SENT', 'Webhook Sent'), ('USER_LOOKUP', 'User Lookup')], max_length=30)),
                ('endpoint', models.CharField(max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='companies_a_company_61dd0e_idx'), models.Index(fields=['company', 'event_type'], name='companies_a_company_5a0dd7_idx')],
            },
        ),
    ]
