# Generated by Django 5.2.11 on 2026-03-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shippingaddress_user_company_user_external_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
    ]
